### ISSUE TITLE
WhoPaysWhat integration

### ISSUE THREAD

**Issue by Ishadijcks** [ortix/food#2]
After closing a list, the groceryshopper should be able to enter an amount that automatically enters it in a WhoPaysWhat-like application

**Comment by ortix** [comment]
Not possible, WBW does not have an API

**Comment by Ishadijcks** [comment]
Correct, but I believe this feature is so significant it merits a change in money-splitting service.

I could poll the team if they are willing to switch to another service?

**Comment by ortix** [comment]
That would be nice, if you can find one! Or just start nagging WBW
